# Generated by Django 4.1.7 on 2023-03-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='file',
        ),
    ]
